### ISSUE TITLE
Use of `@Slot`

### ISSUE THREAD

**Issue by cpeck-rmvd** [starlingcode/viaflash#10]
AFAIK the `@Slot` tag is just used to tag and add arguments to python functions. IE `@Slot()` doesn't really do anything, I think.

@Slot()](https://doc.qt.io/qtforpython/PySide6/QtCore/Slot.html)

LMK if I'm wrong.

**Comment by liquidcitymotors** [comment]
Please see the note on this page: https://doc.qt.io/qtforpython/tutorials/basictutorial/clickablebutton.html
