### ISSUE TITLE
What necessitates all this timing/blocking stuff?

### ISSUE THREAD

**Issue by cpeck-rmvd** [starlingcode/viaflash#16]
https://github.com/starlingcode/viaflash/blob/master/dfu_util.py

What necessitates all of the thread-blocking sort of stuff for this file, it looks like you are reading/writing file(s)? Pulling some stuff from C(++)? Python's got pretty good async-await for stuff like this, not 100% sure it's what you're looking for

https://www.twilio.com/blog/working-with-files-asynchronously-in-python-using-aiofiles-and-asyncio

**Comment by liquidcitymotors** [comment]
This is a wrapper for [dfu-util](http://dfu-util.sourceforge.net/). Some commands complete almost instantly, some take up to a minute to transfer data over USB with a text mode progress bar dumped to stdout. ```subprocess.run``` is easy to use but blocking, ```subprocess.Popen``` needs to be used for the commands that take long enough to complete that they necessitate a progress bar. There is still a problem here, but its more accurately described in https://github.com/starlingcode/viaflash/issues/18
