### ISSUE TITLE
Do the .ui files need to be included in the repo?

### ISSUE THREAD

**Issue by cpeck-rmvd** [starlingcode/viaflash#3]
The .ui files are just generated from accompanying .py files. Do they need to be included in the repo or can we gitignore to save some bloat?

**Comment by liquidcitymotors** [comment]
Other way around, .ui files are created and edited in qtcreator/qtdesigner and the ui_*.py files are generated by the pyside6-uic tool. Those python files could be removed from the repo and generated as part of a build process. I'll keep this open and see whether an actual build script ever gets implemented when the project is more mature.
