### ISSUE TITLE
Allow arbitrary SYNC3 ratio ordering per scale

### ISSUE THREAD

**Issue by liquidcitymotors** [starlingcode/viaflash#33]
Good suggestion from  @hecanjog to not force the user to sort ratios in ascending order. You would also probably want to allow the user to include duplicate ratios. This would allow you to scan through a more or less arbitrary sequence of ratios with a monotonic control signal (think different arpeggio patterns).

**Comment by liquidcitymotors** [comment]
@hecanjog I believe the deed is done

**Comment by hecanjog** [comment]
> @hecanjog I believe the deed is done

exciting!!
