### ISSUE TITLE
GNU GPL license?

### ISSUE THREAD

**Issue by cpeck-rmvd** [starlingcode/viaflash#5]
You need to sometimes be really careful what version of GPL you use in public repos; especially if you're using copyleft (https://en.wikipedia.org/wiki/Copyleft) you aren't really protecting yourself at all from potential liability, just the original authors' code. Maybe you know this.

**Comment by liquidcitymotors** [comment]
Someone who knows and cares more than me about free software licenses chose the license, seems messier to change it now that it has been released under the chosen license.

**Comment by cpeck-rmvd** [comment]
Totally would leave it as is if it was me.. butthe licensing is one of the
most annoying parts to me about using open sources.

You may know all this info, but I actually was at a lawyer-less startup
that had a scare here;

The 3.0 license is totally standard and AFAIK is basically foolproof to
protect a repo provided it covers all potentially liable code.

As is probably obvious, the point is, "hey, copy, share, alter, distribute
this code at will, however YOU are responsible for any and all misuse or
malicious use liability if such a situation arises.



We had a junior dev copy over a license and without changing the license
add some seemingly benign, to him.. but managed to expose some admin
functionality to a portion of end users. Could've been destructive to the
point of litigation but we escaped that by happenstance, got bought out by
this giant oil company with 10k lawyers.

Anyway you know yours is g2g, but I was surprised how serious that got.
